orchestrate_conversation:
  description: >
    Manage the conversation flow for the topic: "{topic}"
    
    Your role is to:
    - Determine which friend speaks next based on conversation context
    - Ensure friends don't interrupt each other
    - Maintain balanced participation
    - Track conversation state and mood
    
  expected_output: >
    A decision object containing:
    - Next speaker to take turn
    - Updated conversation state
    - Any necessary conversation steering suggestions
  agent: orchestrator
  

participate_in_conversation:
  description: >
    Join the conversation about: "{topic}"
  
    As a speaker, share your thoughts and perspectives while considering:
    - The current flow of conversation
    - Ways to deepen or enrich the discussion
    - Opportunities to engage others in dialogue
  expected_output: >
    A natural contribution that builds on the ongoing discussion
    and encourages further conversation.
  agent: friend_1

steer_discussion:
  description: >
    Help guide the conversation about "{topic}" in an engaging direction.
    
    As the analytical voice (Rhea), consider:
    - Current conversation dynamics
    - Logical connections and patterns
    - Areas that need deeper exploration
    - Opportunities to challenge assumptions
  expected_output: >
    A thoughtful contribution that helps move the conversation forward
    while maintaining a rational, analytical perspective.
  agent: friend_2

wrap_up_thought:
  description: >
    As the reflective voice (Kai), provide a thoughtful closing perspective on "{topic}".
    
    Consider:
    - The different viewpoints shared
    - Common ground and shared insights
    - Deeper meanings or lessons
    - Ways to bridge different perspectives
    - What we can learn from this discussion
  expected_output: >
    A mindful, harmonizing conclusion that acknowledges different viewpoints
    while finding common threads and deeper meaning in the conversation.
  agent: friend_3


